version: '3'
services:
    jenkins:
        build: ./jenkins
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - /Users/brendanwatson/OneDrive - Goldex Technologies Limited/IdeaProjects/goldexapp/goldex-eldorado/eldorado-db-schema:/pipeline-dev
        environment:
            JAVA_OPTS: -Djenkins.install.runSetupWizard=false
        ports:
            - "18080:8080"
    nexus:
        image: sonatype/nexus
        ports:
            - "18081:8081"
